services:
  api-gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "80:80"
    depends_on:
      - orchestrator
    networks:
      - brain-network
    restart: unless-stopped

  orchestrator:
    build:
      context: ./orchestrator_service
      dockerfile: Dockerfile
    container_name: orchestrator
    ports:
      - "8080:8080"
    networks:
      - brain-network
    restart: unless-stopped

networks:
  brain-network:
    driver: bridge
    name: brain-network
